dataset:
  name: incels
  inpath: '../../data/incels/all_comments.csv'
  outpath: '../../data/incels/processed_comments'
  load_vocab: False
  tokenize: True
  vocab_path: '../tmp/incels_vocab.json'
  text_column: 'content'

identities:
  name: 'netmapper'
  path: '../resources/generic_agents-identity_v15_2021_10_15.xlsx'
  exclude_path: '../resources/netmapper_exclude.json'
  include_path: '../resources/netmapper_include.json'
