run:
  identity_extraction: True
  action_attribute_extraction: True

dataset:
  name: incels
  #inpath: '../../data/incels/all_comments.csv' # not tokenized
  inpath: '../../data/incels/processed_comments.pkl' # tokenized
  outpath: '../../data/incels/processed_comments'
  tokenize: False
  vocab_path: '../tmp/incels_vocab.json'
  text_column: 'content'

identities:
  name: 'netmapper'
  path: '../resources/generic_agents-identity_v15_2021_10_15.xlsx'
  exclude_path: '../resources/netmapper_exclude.json'
  include_path: '../resources/netmapper_include.json'
  load_vocab: True
